fix: remove enableBundleCompression from build.gradle
Error: MissingPropertyException: Could not set unknown property
'enableBundleCompression' for extension 'react' of type
com.facebook.react.ReactExtension.

This property was generated by expo prebuild but is not supported
in this version of RN's ReactExtension. Removed from:
1. mobile/android/app/build.gradle (local file)
2. build-apk.yml patch step (removes it after each fresh prebuild)